user:
  type:     rest
  resource: AppBundle\Controller\UserController
  prefix : /user

place:
  type:     rest
  resource: AppBundle\Controller\PlaceController
  prefix : /place

persona:
  type:     rest
  resource: AppBundle\Controller\PersonaController
  prefix : /persona