AppBundle\Entity\User:
    constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
                fields: token
                ignoreNull: true
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
                fields: email
                ignoreNull: true
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
                fields: name
                ignoreNull: true
    properties:
#        name:
#            - NotBlank:
#        email:
#            - NotBlank:
#            - Email:
#        password:
#            - NotBlank:
        platform:
            - NotBlank:
            - Type:
                type: int
            - Range:
                min: 1
                max: 2

AppBundle\Entity\Facebook:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: facebookID
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
            ignoreNull: true
    properties:
        facebookID:
            - NotBlank:
            - Type:
                type: int
        email:
            - NotBlank: ~
            - Email:

AppBundle\Entity\Twitter:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: twitterID
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
            ignoreNull: true
    properties:
        twitterID:
            - NotBlank:
            - Type:
                type: int
        email:
            - NotBlank: ~
            - Email:

AppBundle\Entity\Place:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name

    properties:
        name:
            - NotBlank:
            - Length:
                max: 100
        description:
            - NotBlank:
        address:
            - NotBlank:
        lat:
            - NotBlank: ~
            - Type:
                type: float
        lng:
            - NotBlank: ~
            - Type:
                type: float

AppBundle\Entity\Persona:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name

    properties:
        name:
            - NotBlank:
            - Length:
                max: 100
        occupation:
            - NotBlank:
        description:
            - NotBlank:
        wikipedia:
            - Url: ~
        lat:
            - NotBlank: ~
            - Type:
                type: float
        lng:
            - NotBlank: ~
            - Type:
                type: float

AppBundle\Entity\Comment:
    properties:
        text:
            - NotBlank:
            - Length:
                max: 255
        user:
            - NotBlank:
            - Type:
                type: object
        place:
            - NotBlank:
            - Type:
                type: object