AppBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        name:
            expose: true
        email:
            expose: true
        token:
            expose: true
        photo:
            expose: true
        platform:
            expose: true
        facebookId:
            expose: true
        twitterId:
            expose: true
        favouritePlaces:
            expose: true
        favouritePersonas:
            expose: true