AppBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        name:
            expose: true
        email:
            expose: true
        token:
            expose: true
        photo:
            expose: true
        platform:
            expose: true
        facebook:
            expose: true
        twitter:
            expose: true